# Generated by Django 5.0.2 on 2024-02-17 16:02

import basketball.leagueSettings.pDefault
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('height', models.IntegerField()),
                ('formattedHeight', models.CharField(default="0'0", max_length=10)),
                ('weight', models.IntegerField()),
                ('weightModel', models.CharField(choices=[('Lightest', 'Lightest'), ('Lighter', 'Lighter'), ('Light', 'Light'), ('Default', 'Default'), ('Heavy', 'Heavy'), ('Heavier', 'Heavier'), ('Heaviest', 'Heaviest')], default='Default', max_length=10)),
                ('wingspan', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('age', models.CharField(max_length=32)),
                ('archetype', models.CharField(choices=[('Skilled', 'Skilled'), ('Athletic', 'Athletic'), ('Giant', 'Giant')], max_length=10)),
                ('position', models.CharField(choices=[('PG', 'PG'), ('SG', 'SG'), ('SF', 'SF'), ('PF', 'PF'), ('C', 'C')], max_length=2)),
                ('secondaryPosition', models.CharField(choices=[('PG', 'PG'), ('SG', 'SG'), ('SF', 'SF'), ('PF', 'PF'), ('C', 'C')], max_length=2)),
                ('attributes', models.JSONField(blank=True, default=basketball.leagueSettings.pDefault.defaultAttributes)),
                ('badges', models.JSONField(blank=True, default=basketball.leagueSettings.pDefault.defaultBadges)),
                ('tendencies', models.JSONField(blank=True, default=basketball.leagueSettings.pDefault.defaultTendencies)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('titles', models.IntegerField(default=0)),
                ('players', models.ManyToManyField(blank=True, null=True, to='basketball.basketballplayer')),
            ],
        ),
        migrations.AddField(
            model_name='basketballplayer',
            name='currentTeam',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basketball.basketballteam'),
        ),
    ]
