# Generated by Django 5.0.2 on 2024-02-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_alter_basketballplayer_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballteam',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='basketball.basketballplayer'),
        ),
        migrations.AlterField(
            model_name='basketballteam',
            name='titles',
            field=models.IntegerField(default=0),
        ),
    ]
