# Generated by Django 5.0.2 on 2024-02-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_alter_basketballplayer_currentteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballplayer',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
