# Generated by Django 5.0.2 on 2024-02-14 02:17

import basketball.leagueSettings.pDefault
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0004_alter_basketballteam_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballplayer',
            name='attributes',
            field=models.JSONField(blank=True, default=basketball.leagueSettings.pDefault.defaultAttributes),
        ),
        migrations.AlterField(
            model_name='basketballplayer',
            name='badges',
            field=models.JSONField(blank=True, default=basketball.leagueSettings.pDefault.defaultBadges),
        ),
        migrations.AlterField(
            model_name='basketballplayer',
            name='tendencies',
            field=models.JSONField(blank=True, default=basketball.leagueSettings.pDefault.defaultTendencies),
        ),
    ]
