# Generated by Django 5.0.2 on 2024-02-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0005_basketballplayer_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballplayer',
            name='anomaly',
            field=models.BooleanField(default=False),
        ),
    ]
