# Generated by Django 5.0.2 on 2024-02-18 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0006_basketballplayer_anomaly'),
        ('core', '0002_discorduser_my_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballplayer',
            name='discordUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='core.discorduser'),
        ),
    ]
