# Generated by Django 5.0.2 on 2024-02-21 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0009_voucher_voucherreceipt'),
        ('core', '0002_discorduser_my_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherreceipt',
            name='player',
        ),
        migrations.AddField(
            model_name='voucherreceipt',
            name='discordUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.discorduser'),
            preserve_default=False,
        ),
    ]
