# Generated by Django 5.0.2 on 2024-02-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0011_upgradereceipt'),
        ('core', '0004_alter_discorduser_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('taken', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discordUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discorduser')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.basketballplayer')),
            ],
        ),
    ]
