# Generated by Django 5.0.2 on 2024-02-26 00:22

import basketball.leagueSettings.pJumpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0012_cashreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballplayer',
            name='jumpshot',
            field=models.CharField(default=basketball.leagueSettings.pJumpers.rollJumper, max_length=32),
        ),
    ]
