# Generated by Django 5.0.2 on 2024-02-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0013_basketballplayer_jumpshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballplayer',
            name='jumpshot',
            field=models.CharField(blank=True, default='None', max_length=32),
        ),
    ]
