# Generated by Django 5.0.2 on 2024-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='my_players',
            field=models.ManyToManyField(null=True, to='basketball.basketballplayer'),
        ),
    ]
