# Generated by Django 5.0.2 on 2024-02-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_discorduser_my_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
