# Generated by Django 5.0.2 on 2024-02-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0011_upgradereceipt'),
        ('core', '0003_discorduser_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_reward',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='my_players',
            field=models.ManyToManyField(blank=True, null=True, to='basketball.basketballplayer'),
        ),
    ]
