# Django model choices
positionChoices: list[str] = ["PG", "SG", "SF", "PF", "C"]
archetypeChoices: list[str] = ["Skilled", "Athletic", "Giant"]
weightChoices: list[int] = [
    "Lightest",
    "Lighter",
    "Light",
    "Default",
    "Heavy",
    "Heavier",
    "Heaviest",
]


# Default callables for models
def defaultAttributes() -> dict[str, int]:
    return {
        "Driving Layup": 0,
        "Post Fade": 0,
        "Post Hook": 0,
        "Post Moves": 0,
        "Draw Foul": 0,
        "Close Shot": 0,
        "Midrange Shot": 0,
        "3pt Shot": 0,
        "Free Throw": 0,
        "Ball Control": 0,
        "Passing IQ": 0,
        "Pass Accuracy": 0,
        "Offensive Rebound": 0,
        "Standing Dunk": 0,
        "Driving Dunk": 0,
        "Shot IQ": 0,
        "Passing Vision": 0,
        "Hands": 0,
        "Defensive Rebound": 0,
        "Interior Defense": 0,
        "Perimeter Defense": 0,
        "Block": 0,
        "Steal": 0,
        "Lateral Quickness": 0,
        "Speed with Ball": 0,
        "Hustle": 0,
        "Pass Perception": 0,
        "Defensive Consistency": 0,
        "Help Defense IQ": 0,
        "Offensive Consistency": 0,
        "Intangibles": 0,
        "Speed": 0,
        "Acceleration": 0,
        "Vertical": 0,
        "Strength": 0,
    }


def defaultBadges() -> dict[str, int]:
    return {
        # Shooting badges
        "Agent 3": 0,
        "Blinders": 0,
        "Catch & Shoot": 0,
        "Claymore": 0,
        "Comeback Kid": 0,
        "Corner Specialist": 0,
        "Deadeye": 0,
        "Free Points": 0,
        "Green Machine": 0,
        "Guard Up": 0,
        "Limitless Range": 0,
        "Middy Magician": 0,
        "Open Looks": 0,
        "Post Fade Phenom": 0,
        "Slippery OFf-Ball": 0,
        "Space Creator": 0,
        "Spot Finder": 0,
        # Playmaking badges
        "Ankle Breaker": 0,
        "Bail Out": 0,
        "Blow-By": 0,
        "Break Starter": 0,
        "Dimer": 0,
        "Handles for Days": 0,
        "Hyperdrive": 0,
        "Killer Combos": 0,
        "Needle Threader": 0,
        "Physical Handles": 0,
        "Post Playmaker": 0,
        "Relay Passer": 0,
        "Special Delivery": 0,
        "Speed Booster": 0,
        "Touch Passer": 0,
        "Triple Spike": 0,
        "Unpluckable": 0,
        # Finishing badges
        "Acrobat": 0,
        "Aerial Wizard": 0,
        "Backdown Punisher": 0,
        "Big Driver": 0,
        "Bulldozer": 0,
        "Bunny": 0,
        "Dream Shake": 0,
        "Dropstepper": 0,
        "Fast Twitch": 0,
        "Fearless Finisher": 0,
        "Float Game": 0,
        "Giant Slayer": 0,
        "Hook Specialist": 0,
        "Masher": 0,
        "Post Spin Technician": 0,
        "Posterizer": 0,
        "Precision Dunker": 0,
        "Pro Touch": 0,
        "Rise Up": 0,
        "Scooper": 0,
        "Slithery": 0,
        "Spin Cycle": 0,
        "Two Step": 0,
        "Whistle": 0,
        #  Defensive badges
        "94 Feet": 0,
        "Anchor": 0,
        "Ankle Braces": 0,
        "Boxout Beast": 0,
        "Brick Wall": 0,
        "Challenger": 0,
        "Chase Down Artist": 0,
        "Clamps": 0,
        "Fast Feet": 0,
        "Glove": 0,
        "Interceptor": 0,
        "Immovable Enforcer": 0,
        "Off-Ball Pest": 0,
        "Pick Dodger": 0,
        "Pogo Stick": 0,
        "Post Lockdown": 0,
        "Rebound Chaser": 0,
        "Right Stick Ripper": 0,
        "Work Horse": 0,
    }


def defaultTendencies() -> dict[str, int]:
    return {}
